language: cpp
os: linux
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - qtbase5-dev

matrix:
  include:
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - compiler: clang
    - compiler: clang
      env:
        - MATRIX_EVAL="USING_CMAKE=1"

before_install:
  - eval "${MATRIX_EVAL}"
  - qmake -v

script:
  - cd ./build
  - if [ $USING_CMAKE -eq 1 ]; then
      cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt;
      make;
      export IPC_TARGET=test-ipc;
    else
      qmake -o Makefile ipc.pro QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_LINK=$CXX;
      qmake -o MakefileTest test.pro QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_LINK=$CXX;
      cat MakefileTest;
      make;
      make -f MakefileTest;
      export IPC_TARGET=test;
    fi
  - export LD_LIBRARY_PATH=../output:$LD_LIBRARY_PATH && ../output/$IPC_TARGET

notifications:
  slack:
    on_success: never
    on_failure: never
