language: cpp
os: linux
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - qt5-qmake
      - libqt5test5

matrix:
  include:
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - compiler: clang
    - compiler: clang
      env:
        - MATRIX_EVAL="USING_CMAKE=1"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - qmake -v
  - cd ./build
  - if [ $USING_CMAKE -eq 1 ]; then
      cmake -DCMAKE_BUILD_TYPE=Release CMakeLists.txt
      make
    else
      qmake -o Makefile ipc.pro QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_LINK=$CXX
      qmake -o MakefileTest test.pro QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_LINK=$CXX
      make
      make -f MakefileTest
    fi
  - export LD_LIBRARY_PATH=../output:$LD_LIBRARY_PATH && ../output/test

notifications:
  slack:
    on_success: never
    on_failure: never
